<?php

class CUespDestiny2WordPressData
{
	
	// Below here is autogenerated content...do not modify
const DATA_SUPERABILITIES = array (
  2274196886 => 
  array (
    'name' => 'Daybreak',
    'desc' => 'Fashion Solar Light into blades and smite your foes from the sky.

Your Daybreak projectiles launch a streak of deadly flames on impact.',
    'icon' => '/common/destiny2_content/icons/ce006cb360a96d8f054e49499d924603.png',
  ),
  2274196887 => 
  array (
    'name' => 'Well of Radiance',
    'desc' => 'Thrust your Sword into the ground, damaging and scorching nearby targets. The Sword projects a continuous aura, granting restoration and radiant effects to nearby allies, protecting them from the effects of Stasis.',
    'icon' => '/common/destiny2_content/icons/5dbb9a2f285df3ee20fe37d073350a37.png',
  ),
  2625980631 => 
  array (
    'name' => 'Silence and Squall',
    'desc' => 'Summon two Stasis kamas, Silence and Squall, that you throw one after another.

Silence : Creates a flash-freeze blast that freezes and damages targets.

Squall : Creates a Stasis Storm that slows and damages targets caught inside.',
    'icon' => '/common/destiny2_content/icons/bac0872a1d59eb9a6f3a0ca7f349b8cc.png',
  ),
  2722573681 => 
  array (
    'name' => 'Shadowshot: Moebius Quiver',
    'desc' => 'Tether foes to a Void Anchor, weakening and suppressing them for you and your allies.

Fire two volleys of three Void Arrows that seek nearby targets. Shadowshot makes targets volatile and deals increased damage to tethered targets. Defeating tethered targets creates Orbs of Power.',
    'icon' => '/common/destiny2_content/icons/af58a42be4e803d1b5a7885b13985977.png',
  ),
  2722573682 => 
  array (
    'name' => 'Spectral Blades',
    'desc' => 'Summon a pair of deadly Void blades and stalk the battlefield in a veil of shadows.
[Light Attack]  : Perform a quick melee attack.
[Heavy Attack]  : Perform a heavy attack and once again vanish from sight.',
    'icon' => '/common/destiny2_content/icons/a219dacf9847a5c6174d096ce394e460.png',
  ),
  2722573683 => 
  array (
    'name' => 'Shadowshot: Deadfall',
    'desc' => 'Tether foes to a Void Anchor, weakening and suppressing them for you and your allies.

The Void Anchors fired from Shadowshot pull targets toward the impact point, which then become traps and wait for prey. Void Anchors have increased range and last longer.',
    'icon' => '/common/destiny2_content/icons/a30563f95eea66ef729a4e65a7152fa7.png',
  ),
  2747500760 => 
  array (
    'name' => 'Burning Maul',
    'desc' => 'Summon a flaming maul and crush your enemies with the force of an earthquake.

[Light Attack]  : Spin the maul in a circle around you, damaging nearby targets.

[Heavy Attack]  : Slam the maul to the ground and create a cyclone of flames that seeks targets.',
    'icon' => '/common/destiny2_content/icons/81b0c61ff8ac802d3216324028b7e835.png',
  ),
  2747500761 => 
  array (
    'name' => 'Hammer of Sol',
    'desc' => 'Summon a flaming hammer and wreak destruction down upon your enemies.

[Light Attack]  : Throw your hammer at foes.

Upon impact, your hammers shatter into explosive molten shards.',
    'icon' => '/common/destiny2_content/icons/746ed830d614d66f57d379811a57d03d.png',
  ),
  3683904166 => 
  array (
    'name' => 'Winter\'s Wrath',
    'desc' => 'Summon a [Stasis] Stasis staff. While your Super is active:

[Super Primary]  : Cast out a barrage of [Stasis] Stasis shards that freeze targets.

[Super Secondary]  : Cast out a shockwave that shatters all frozen targets.',
    'icon' => '/common/destiny2_content/icons/3adf16d07aab7c46551bd1bfa9e2e283.png',
  ),
  3769507632 => 
  array (
    'name' => 'Gathering Storm',
    'desc' => 'Hurl your Arc Staff forward, embedding it into surfaces or large targets and jolting nearby targets.

After a short time, a devastating lightning bolt strikes the staff, overcharging it with Arc energy. While overcharged, your staff discharges lightning at nearby foes.',
    'icon' => '/common/destiny2_content/icons/5919e3e43ab455cee03ff23cdaa23080.png',
  ),
  3769507633 => 
  array (
    'name' => 'Arc Staff',
    'desc' => 'Form a staff of pure Arc energy and acrobatically take out your foes.

[Block] : Hold to deflect incoming projectiles with your Arc staff.',
    'icon' => '/common/destiny2_content/icons/022d0ea9e0ca89294bb1c9cef65273b8.png',
  ),
  4260353952 => 
  array (
    'name' => 'Sentinel Shield',
    'desc' => '[Super]  : Summon a shield of Void Light. 
While Sentinel Shield is active:
[Light Attack]  : Attack.
[Block]  : Block.
[Grenade]  : Perform a Shield Throw.

Guard with Sentinel Shield to create a defensive wall. Allies who shoot through the wall have increased weapon damage, and guarding allies makes the shield last longer.',
    'icon' => '/common/destiny2_content/icons/f02fd0d90b8d3d7182b9c7cab1a46f64.png',
  ),
  4260353953 => 
  array (
    'name' => 'Ward of Dawn',
    'desc' => 'Create an indestructible dome to protect you and your allies. Passing through Ward of Dawn grants you and your allies a temporary increase to weapon damage.',
    'icon' => '/common/destiny2_content/icons/91eec50f00de84db8b666ec299859a21.png',
  ),
  119041298 => 
  array (
    'name' => 'Thundercrash',
    'desc' => 'Hurtle through the air like a missile and crash into targets to inflict meteoric damage.',
    'icon' => '/common/destiny2_content/icons/4e03473a24049bdb6013badca6b61965.png',
  ),
  119041299 => 
  array (
    'name' => 'Fists of Havoc',
    'desc' => 'Supercharge your fists and slam the ground with the force of a maelstrom. While active:

[Light Attack]  : Quickly charge forward, dealing damage to any impacted targets.

[Heavy Attack] : Slam your fists to the ground, dealing damage in an area around you and leaving aftershocks in your wake. Performing a slam from the air deals additional damage.',
    'icon' => '/common/destiny2_content/icons/20f5a1879f8562e3ce6c0140b0e2fd8d.png',
  ),
  375052468 => 
  array (
    'name' => 'Golden Gun - Marksman',
    'desc' => 'Summon a precision flaming pistol that disintegrates targets with Solar Light.

Your Golden Gun deals massively increased precision damage, overpenetrates targets, and creates Orbs of Power on precision hits.

Benefits from being radiant.',
    'icon' => '/common/destiny2_content/icons/6f3e329cf7d330f7ba0cd0f940e98110.png',
  ),
  375052469 => 
  array (
    'name' => 'Golden Gun - Deadshot',
    'desc' => 'Summon a rapid-fire flaming pistol that disintegrates targets with Solar Light.

Causing Solar ignitions while your Super is active refunds a Golden Gun round.

Benefits from being radiant.',
    'icon' => '/common/destiny2_content/icons/16e3aaf50ac9fa802b692af48b895886.png',
  ),
  375052471 => 
  array (
    'name' => 'Blade Barrage',
    'desc' => 'Vault into the air and unleash a volley of Solar-charged explosive knives.',
    'icon' => '/common/destiny2_content/icons/5178685d628a640be304950a6b7da11f.png',
  ),
  1081893460 => 
  array (
    'name' => 'Stormtrance',
    'desc' => 'Chain Arc Lightning from your hands to electrify targets with devastating streams of Arc Light that intensify over time. Casting Stormtrance creates a shockwave underneath you.

[Sprint]  : Teleport forward, consuming a small amount of Super energy.',
    'icon' => '/common/destiny2_content/icons/2dd43a50e48bab5c297c8459bc125bd2.png',
  ),
  1081893461 => 
  array (
    'name' => 'Chaos Reach',
    'desc' => 'Unleash a long-range channeled beam of concentrated Arc energy.

 [Super]  while active to deactivate your Super early, saving Super energy.',
    'icon' => '/common/destiny2_content/icons/c1e711eb4bd8ee24a257fd83a635054c.png',
  ),
  1656118680 => 
  array (
    'name' => 'Nova Warp',
    'desc' => 'Step between dimensions to subvert the laws of physics.
[Super Secondary]  : Teleport a short distance.
[Super Primary]  : Unleash a deadly Void eruption.',
    'icon' => '/common/destiny2_content/icons/82a9885b09a090770b56f21927df9d03.png',
  ),
  1656118681 => 
  array (
    'name' => 'Nova Bomb: Vortex',
    'desc' => 'Hurl an explosive bolt of Void Light at a target, disintegrating those caught within its blast.

Nova Bomb creates a singularity that pulls targets inward and continually damages those trapped inside.',
    'icon' => '/common/destiny2_content/icons/0230272ce6d6d6ed1d1a3a951e460f34.png',
  ),
  1656118682 => 
  array (
    'name' => 'Nova Bomb: Cataclysm',
    'desc' => 'Hurl an explosive bolt of Void Light at a target, disintegrating those caught within its blast.

Nova Bomb travels slowly and seeks targets. Detonations shatter into smaller seeker projectiles.',
    'icon' => '/common/destiny2_content/icons/fd0d80cb5f7c0f777795ab3d1b701f4f.png',
  ),
  2021620139 => 
  array (
    'name' => 'Glacial Quake',
    'desc' => 'Summon a [Stasis] Stasis gauntlet. While your Super is active:

[Heavy Attack]  : Slam your gauntlet down to create a shockwave that freezes targets and sends out [Stasis] Stasis crystals to freeze additional ones.

[Light Attack]  : Supercharge your Shiver Strike for bonus damage. Sprint through [Stasis] Stasis crystals or frozen targets to shatter them instantly.',
    'icon' => '/common/destiny2_content/icons/a764f6e02c1912967ea8e2b701d90cfd.png',
  ),
);
//-----------------------------------------------------------------------------

const DATA_CLASSABILITIES = array (
  2209081648 => 
  array (
    'name' => 'Empowering Rift',
    'desc' => 'Conjure a well of power that increases weapon damage for those inside it.',
    'icon' => '/common/destiny2_content/icons/eaccd2b0e0321fa9842313d188ddc2ef.jpg',
  ),
  2209081649 => 
  array (
    'name' => 'Healing Rift',
    'desc' => 'Conjure a well of power that continuously heals those inside it.',
    'icon' => '/common/destiny2_content/icons/725c7d76abfb19121f358c04bbd623dc.jpg',
  ),
  2495523340 => 
  array (
    'name' => 'Towering Barricade',
    'desc' => 'Create a large barrier that can be used to reinforce a position with cover from enemy fire.',
    'icon' => '/common/destiny2_content/icons/ac96e6784aee2e7011c720eca39fd531.png',
  ),
  2495523341 => 
  array (
    'name' => 'Rally Barricade',
    'desc' => 'Create a small barrier that you can peek over while aiming down sights and that increases weapon reload speed, stability, and range when you stand behind it.',
    'icon' => '/common/destiny2_content/icons/ced8899f7ff33bf58c0e0ec5c5da5666.png',
  ),
  2816982784 => 
  array (
    'name' => 'Marksman\'s Dodge',
    'desc' => 'Dodge to perform an evasive maneuver with a steady hand. Dodging automatically reloads your weapon.',
    'icon' => '/common/destiny2_content/icons/bca550b5e1e2db9e3ec358c22f6984c0.jpg',
  ),
  2816982785 => 
  array (
    'name' => 'Gambler\'s Dodge',
    'desc' => 'Dodge to perform a deft tumble, avoiding enemy attacks. Dodging near enemies fully recharges your Melee Ability.',
    'icon' => '/common/destiny2_content/icons/3536ce85290691269b0fabac3d7e760d.jpg',
  ),
  2979486801 => 
  array (
    'name' => 'Phoenix Dive',
    'desc' => 'Dive to the ground and create a burst of Solar Light that cures nearby allies.

While Heat Rises is active, you gain restoration while diving and scorch targets upon landing.',
    'icon' => '/common/destiny2_content/icons/85ef85819a19d528c86a6329ea895fb5.jpg',
  ),
  3636300852 => 
  array (
    'name' => 'Acrobat\'s Dodge',
    'desc' => 'Dodge to perform an acrobatic leap. Upon landing, make yourself and nearby allies radiant.',
    'icon' => '/common/destiny2_content/icons/18b507607e6971bb10fec7addc24786b.jpg',
  ),
  489583098 => 
  array (
    'name' => 'Thruster',
    'desc' => 'While grounded, quickly evade in a lateral direction.',
    'icon' => '/common/destiny2_content/icons/76b275a4b8547f96bba2b7324b0fc4a0.jpg',
  ),
);
//-----------------------------------------------------------------------------

const DATA_MOVEMENTABILITIES = array (
  2225231092 => 
  array (
    'name' => 'High Lift',
    'desc' => 'Jump while airborne to activate Lift and launch into the air to greater heights.',
    'icon' => '/common/destiny2_content/icons/9844e49a2c2aeba27fdf11075317b3b2.png',
  ),
  2225231093 => 
  array (
    'name' => 'Strafe Lift',
    'desc' => 'Jump while airborne to activate Lift and launch into the air with strong directional control.',
    'icon' => '/common/destiny2_content/icons/45a08dcdcdc4ebcc5690ab027027cb0a.png',
  ),
  2225231094 => 
  array (
    'name' => 'Catapult Lift',
    'desc' => 'Jump while airborne to activate Lift and launch into the air with a strong initial burst of momentum.',
    'icon' => '/common/destiny2_content/icons/6af35cff95ec2c86847bfedcfe7fc62d.png',
  ),
  3531427692 => 
  array (
    'name' => 'Triple Jump',
    'desc' => 'While airborne, sustain your air control with a second or third jump.',
    'icon' => '/common/destiny2_content/icons/78db4441ec50dc42411ac27a32d99d70.png',
  ),
  3531427694 => 
  array (
    'name' => 'High Jump',
    'desc' => 'While airborne, jump a second time to reach greater heights.',
    'icon' => '/common/destiny2_content/icons/16a4b21bcf60643a3305f8fe32908632.png',
  ),
  3531427695 => 
  array (
    'name' => 'Strafe Jump',
    'desc' => 'While airborne, jump a second time with strong directional control.',
    'icon' => '/common/destiny2_content/icons/0249bf706815f930cbdf78bc25e1732d.png',
  ),
  3686638441 => 
  array (
    'name' => 'Balanced Glide',
    'desc' => 'Jump while airborne to activate Glide and start an airborne drift with both moderate speed and directional control.',
    'icon' => '/common/destiny2_content/icons/3d0b1e371face8fe7cd9e2646e2ecdea.png',
  ),
  3686638442 => 
  array (
    'name' => 'Burst Glide',
    'desc' => 'Jump while airborne to activate Glide and start an airborne drift with a strong initial boost of speed.',
    'icon' => '/common/destiny2_content/icons/26af42f4af7025280741b4c4a18eaacc.png',
  ),
  3686638443 => 
  array (
    'name' => 'Strafe Glide',
    'desc' => 'Jump while airborne to activate Glide and start an airborne drift with strong directional control.',
    'icon' => '/common/destiny2_content/icons/be1d77ea4eebee140ae0cdc93493ec34.png',
  ),
  95544329 => 
  array (
    'name' => 'Blink',
    'desc' => 'Jump while airborne to teleport a short distance.',
    'icon' => '/common/destiny2_content/icons/8851d08581396b63da4c5c5acbc3f9e7.jpg',
  ),
);
//-----------------------------------------------------------------------------

const DATA_ARCGRENADE = array (
  2481624867 => 
  array (
    'name' => 'Storm Grenade',
    'desc' => 'A grenade that calls down a focused lightning storm.',
    'icon' => '/common/destiny2_content/icons/ce01ccf413b2ae6e991f6cef3f226aaa.jpg',
  ),
  2909720723 => 
  array (
    'name' => 'Flashbang Grenade',
    'desc' => 'An explosive grenade that damages and blinds nearby targets.',
    'icon' => '/common/destiny2_content/icons/9ca15ccec054e10cfe44db67331bbb6b.jpg',
  ),
  2994412667 => 
  array (
    'name' => 'Lightning Grenade',
    'desc' => 'A grenade that sticks to any surface and emits bolts of lightning.',
    'icon' => '/common/destiny2_content/icons/6cbbd606e7d696eab7d54a49ba8a9c0a.jpg',
  ),
  4198689901 => 
  array (
    'name' => 'Flux Grenade',
    'desc' => 'An explosive grenade that attaches to targets.',
    'icon' => '/common/destiny2_content/icons/9a30af5e62d440a3f201b307e19e54e0.jpg',
  ),
  146194908 => 
  array (
    'name' => 'Skip Grenade',
    'desc' => 'A grenade that splits upon impact, creating multiple projectiles that seek targets.',
    'icon' => '/common/destiny2_content/icons/506b6803d54790304775545568d1f9e9.jpg',
  ),
  1582574009 => 
  array (
    'name' => 'Arcbolt Grenade',
    'desc' => 'A grenade that chains bolts of lightning to nearby targets.',
    'icon' => '/common/destiny2_content/icons/1d4e4334f59a2369a0558452d686d3d0.jpg',
  ),
  1713935764 => 
  array (
    'name' => 'Pulse Grenade',
    'desc' => 'A grenade that periodically damages targets within its explosion radius.',
    'icon' => '/common/destiny2_content/icons/a1f1c4b248bf506739a9888949ca7e57.jpg',
  ),
);
//-----------------------------------------------------------------------------

const DATA_ARCMELEE = array (
  2708585276 => 
  array (
    'name' => 'Ballistic Slam',
    'desc' => 'After sprinting and while airborne, activate your charged melee ability to slam to the ground, dealing damage to nearby enemies.',
    'icon' => '/common/destiny2_content/icons/f77b830430f5522ee47564b3b33e5035.png',
  ),
  2708585277 => 
  array (
    'name' => 'Seismic Strike',
    'desc' => 'After sprinting for a short time, activate your charged melee ability to slam shoulder-first into your target, damaging and Blinding enemies in an area around them.

While you are Amplified, the Blind radius is increased.',
    'icon' => '/common/destiny2_content/icons/ee94e210e84ff1d0b3e969205e0ad4f7.png',
  ),
  2708585279 => 
  array (
    'name' => 'Thunderclap',
    'desc' => '[Melee] : Hold while grounded to plant your feet and begin charging your fist with Arc energy.

[Melee] : Release to unleash a devastating blast in front of you, dealing damage that increases with longer charge time.',
    'icon' => '/common/destiny2_content/icons/7cd4d54c709dee898f8bee89d3855f14.png',
  ),
  2716335210 => 
  array (
    'name' => 'Disorienting Blow',
    'desc' => 'Striking an enemy with this melee ability Blinds them and Amplifies you.',
    'icon' => '/common/destiny2_content/icons/512bf5353df73da7a34e0e885e9f9c40.png',
  ),
  2716335211 => 
  array (
    'name' => 'Combination Blow',
    'desc' => 'A quick strike that temporarily increases your melee damage when defeating a target, stacking three times.

Defeating targets with this ability also fully refills your class ability energy and restores a small amount of health.',
    'icon' => '/common/destiny2_content/icons/04122696634d1ec7290dd380434c45d3.png',
  ),
  1232050830 => 
  array (
    'name' => 'Ball Lightning',
    'desc' => 'Fire an Arc projectile forward that releases a perpendicular lightning strike after a short time.

While Amplified, Ball Lightning releases additional lightning strikes before detonating.',
    'icon' => '/common/destiny2_content/icons/5a17204b115c8dc65fca864e0db8f269.jpg',
  ),
  1232050831 => 
  array (
    'name' => 'Chain Lightning',
    'desc' => 'An extended range melee that Jolts your target and chains lightning to nearby enemies.

While Amplified, it creates an additional set of chains.',
    'icon' => '/common/destiny2_content/icons/ee73db9fc021bd7ee09cb0bf23c45b45.jpg',
  ),
);
//-----------------------------------------------------------------------------

	
};